### ISSUE TITLE
[questionnaire] Ajouter une question sur le statut PO ou PB

### ISSUE THREAD

**Issue by Mael-21** [betagouv/reno#101]
###  Proposition de reformulation de la question

**[question] Vous êtes :**
[réponses]
1. Propriétaire occupant
2. Propriétaire bailleurs
3. Syndicat de copropriétaires
4. Locataire

**Si choix 3. Syndicat -> écran de transition**

Ce simulateur n’intègre pas encore MaPrimeRénov' Copropriété, les aides de l’État pour la rénovation énergétique des copropriétés. 

N'hésitez pas à faire cette simulation en choisissant le status propriétaire pour évaluer votre éligibilité aux aides individuelles pour la rénovation de votre logement

En tant que locataire, vous n'êtes pas éligible aujourd’hui aux aides à la rénovation.

N'hésitez pas à faire cette simulation comme si vous étiez propriétaire. Cela peut constituer une base de discussion factuelle intéressante : votre propriétaire n'est peut-être pas au courant des nouvelles aides 2024

**

![Image](https://github.com/betagouv/reno/assets/77799453/3253377b-eaf9-4d2f-aa6c-4049a0ad8db4)

**

**Comment by Mael-21** [comment]
A noter : récupérer le statuts permettra également de filtrer les "autres 
 aides" affichées dans l'écran d'éligibilité

**Comment by laem** [comment]
Cette question peut amener une confusion qui n'existe pas aujourd'hui pour les gens qui sont plusieurs propositions à la fois. 

L'immobilier est très concentré en France donc beaucoup de gens sont à la fois propriétaires occupant et bailleurs. D'autres sont locataires mais aussi propriétaire. 

La question actuelle n'a pas ce problème, mais est du coup inexacte. Pour le résoudre il faudrait expliquer à l'utilisateur que la simulation se fait *pour un logement*, que l'utilisateur doit choisir dans sa tête en début de parcours (ou juste dans le titre de la question comme on le fait pour la question 2 actuelle). "Êtes-vous propriétaire du logement ?". 

Aussi je trouve la proposition 3 potentiellement confuse, car je peux être propriétaire mais m'intéresser aux aides pour ma copro, pour ensuite les suggérer aux réunions de copropriété, mais je ne m'identifierai pas forcément à la proposition "syndicat de copro".

**Comment by Mael-21** [comment]
Je suis d'accord avec toi, mais l'ambiguïté sur le multi-proprio existe déjà aujourd'hui. En pratique, on ne donne un résultats qu'à l'échelle d'un seul logement. Par ex. on ne sélectionne qu'un seul DPE, on ne mentionne pas la limite de 3 logements différents maximum, dans la limite de 20 000€ de travaux par logement sur 5 ans... 
-> Je proposerais de déprioriser le cas de la simulation multi-logement tant qu'on ne voit pas qu'il ressort 

Le question de syndicat de copro pose un autre question : ce n'est pas le propriétaire lui-même qui porte la demande (à moins qu'il possède toute la copro). 
-> l'avantage c'est qu'on informe qu'on ne traite pas (encore) ce cas.

**Comment by Mael-21** [comment]
Par contre le PB, c'est que ça ne permet pas de savoir si le logement est individuel ou dans une copro et donc de filtrer les autres aides correspondante...

**Comment by laem** [comment]
Intégré sous la forme "êtes-vous propriétaire occupant" pour le besoin des aides d'Angers

**Comment by laem** [comment]
Fait
