### ISSUE TITLE
[questionnaire] Je ne suis pas propriétaire

### ISSUE THREAD

**Issue by Mael-21** [betagouv/reno#102]
Éviter les "cul de sac" en invitant les "non" propriétaire à poursuivre

 

![Image](https://github.com/betagouv/reno/assets/77799453/ddfb6442-2587-44bc-9eff-f001eae15b79)

**Comment by laem** [comment]
![Recording 2024-04-10 at 09 52 42](https://github.com/betagouv/reno/assets/1177762/10a30617-dde3-4bf8-ada7-8389228ad471)

En sachant qu'on le fait déjà, c'est un changement d'UX pour passer d'une notification à un écran supplémentaire dédié au locataire qui nécessite un clic en plus pour avoir l'info.


(j'ai ajouté une animation pour rendre la notif plus visible en attendant)

**Comment by laem** [comment]
Fait
