### ISSUE TITLE
[A propos] Modification du contenu

### ISSUE THREAD

**Issue by Mael-21** [betagouv/reno#104]
Contexte : 
- Ajout de précisions dans le texte sur les partenaires
- correction de quelques coquilles
- Ajout d'un titre "développeur" - dis moi si ça te semble claire @laem 

Proposition : 

### À propos

Mes Aides Réno est un service conçu par la [Direction Interministérielle du Numérique] (https://www.numerique.gouv.fr/dinum/) en partenariat avec avec [France Rénov'](https://france-renov.gouv.fr/) et le [Secrétariat général à la planification écologique (SGPE)] (https://www.info.gouv.fr/france-nation-verte)  

Ce service a pour objectif de pour simplifier l’accès à l’information sur les aides à la rénovation énergétique. Il est incubé par l'incubateur des services numériques de l'État, [beta.gouv](https://beta.gouv.fr/). 

Mes Aides Réno a été lancé en version beta. L’objectif est de le confronter à des usagers pour le faire rapidement évoluer en fonction des premiers retours. Vous pouvez en apprendre davantage sur le problème que nous souhaitons résoudre, les solutions que nous expérimentons et comment nous comptons en étudier l'impact en lisant notre [fiche produit](https://www.beta.gouv.fr/startups/mesaidesreno.html).

#### Développeurs

Mes Aides Réno a été conçu pour être facilement réutilisable et intégrable par des services tiers. 

Le code du site [est intégralement ouvert](https://github.com/betagouv/reno), et basé sur des bibliothèques elles-même ouvertes.
Le code métier est basé sur le langage [Publicodes](https://publi.codes/) pour maximiser son ouverture et sa lisibilité. Une API est disponible pour comprendre notre modèle métier et réutiliser les données https://mesaidesreno.beta.gouv.fr/api-doc.

#### Mentions légales

Ce site Web est opéré par la [Direction Interministérielle du Numériques](https://annuaire-entreprises.data.gouv.fr/entreprise/direction-interministerielle-du-numerique-dinum-130025265). Il est hébergé sur un serveur français, comme expliqué sur la page [confidentialité](https://mesaidesreno.beta.gouv.fr/confidentialite).

**Comment by laem** [comment]
:+1: 

Je te propose comme titre 2 "Partenaires et développeurs" pour pas limiter seulement à un public de dev. 

Aussi, plutôt que "confronter aux usagers" je propose "mettre dans la main des usagers" car "confronter" sonne un peu conflictuel je trouve ^^.
