### ISSUE TITLE
[Home] Affiche et alignement des logos

### ISSUE THREAD

**Issue by Mael-21** [betagouv/reno#106]
1 - Défaut d'alignement 
- Aligner le bloc 1er écran avec le logo FR' (ou tester le logo FR' à droite de l'écran)

2) Mobile / destkop
- En affichage desktop, mettre le teste FR' et le logo FR' sur une seul ligne
- En mobile, le logo FR' se place au dessus du texte, ferré à gauche (comme maintenant)

3) Illustration 
- Sur mobile, supprimer l'illustration de manière a ce que le logo FR' soit visible sur le premier écran

**Comment by laem** [comment]
Fait en direct avec 5d7dcd9e7276dbef9b5df003accf7afe4131a548 et 40216680ee02b0d78ba69492aeb6ab6695eabe09
