### ISSUE TITLE
[MPRA] Bug changement de DPE

### ISSUE THREAD

**Issue by Mael-21** [betagouv/reno#107]
Sujet évoqué hier : 
Sur l'écran MPRA, lorsque je modifie mon DPE déclaré, la box résultat ne se met pas à jour avec les bons DPE correspondant aux 2 saut de classe. 

Autre pb (bcp moins critique) : Sur desktop, je peux choisir une valeur négative sur dans "mon apport"

**Comment by laem** [comment]
C'est géré normalement, je te laisse vérifier.
