### ISSUE TITLE
Vérifier l'écrêtement 

### ISSUE THREAD

**Issue by laem** [betagouv/reno#153]
http://localhost:8080/simulation?simulation.mode=%27max%27*&vous.propri%C3%A9taire.condition=oui*&logement.propri%C3%A9taire+occupant=oui*&logement.r%C3%A9sidence+principale+propri%C3%A9taire=oui*&logement.p%C3%A9riode+de+construction=%22au+moins+15+ans%22*&m%C3%A9nage.personnes=3*&m%C3%A9nage.code+r%C3%A9gion=%2252%22*&m%C3%A9nage.EPCI=%22244900015%22&m%C3%A9nage.commune=%2249007%22*&m%C3%A9nage.revenu=23934*&DPE.actuel=6*&objectif=MPR.accompagn%C3%A9e.montant&projet.DPE+vis%C3%A9=2

**Comment by morganmerzouk** [comment]
voici un lien qui détaille bien le mode de calcul de l'écrêtement: https://faq.hellio.com/regle-ecretement-maprimerenov
