### ISSUE TITLE
Amélioration des cas d'utilisation sur l'accueil 

### ISSUE THREAD

**Issue by laem** [betagouv/reno#173]
- [x] Utiliser les balises summary/details à la place du voir plus
- [x] Faire ressortir les infos importantes (mettre les lettres de DPE en couleur, les montants dans leur box bleu clair)
- [ ] Faire paraitre le résultat directement, avant "Voir plus"

**Comment by laem** [comment]
Après réflexion, je pense qu'il faut variabiliser ces cas, que ce soit juste des personas++, pour éviter d'inscrire en dur des chiffres qui pourront évoluer sans qu'on pense à les changer.

**Comment by morganmerzouk** [comment]
- [] Ne pas oublier de faire évoluer ses histoires en fonction des évolutions de la réglementation
- [] Changer le wording du "Voir plus" pour quelque chose de plus explicite "Ses aides"
