### ISSUE TITLE
Mauvaise recommandation d'espace ECFR

### ISSUE THREAD

**Issue by laem** [betagouv/reno#196]
Pour certaines communes, l'espace France Rénov vers lequel est orienté le demandeur en fonction du code postal saisi n’est pas le bon.
 
Exemple:
En renseignant la commune "Nesle" dans le 80, l'espace FR désigné est Habitat Rénové à Compiègne dans l'Oise (alors que l’espace FR de référence est APREMIS à Amiens).
Idem, commune 60400 Appilly = Habitat Rénové alors que l'ECFR est l'ADIL de l'Oise
Autre exemple : commune 60620 Betz = orientation vers un ECFR du 77 au lieu de l'ADIL de l'Oise
 
Peut-être une confusion code postal/code INSEE ?

**Comment by morganmerzouk** [comment]
#188 est un doublon que je ferme

**Comment by laem** [comment]
Si c'est encore un problème de "ECFR officiel versus un autre type de lieu de conseil", tu as vu ce commentaire ? 

> Je ne sais pas comment filtrer uniquement les ECFR. Il faut osculter les données https://api-lannuaire.service-public.fr/api/explore/v2.1/catalog/datasets/api-lannuaire-administration/exports/csv et trouver le paramètre qui nous permet de les filtrer.

Autre point : peut-être qu'un simple match sur les termes suffirait.

**Comment by morganmerzouk** [comment]
Oui on arriverai à ne proposer que les ECFR "officiel", mais j'ai étudié cette BDD et on n'a aucun moyen de savoir exactement quelle commune est rattachée à quel ECFR, ce n'est pas forcément le plus proche géographiquement. 
Un compromis pourrait être d'afficher les 3 plus proches

**Comment by laem** [comment]
Mmmh, en effet j'en viens à la même conclusion que toi. Par contre...

**Comment by laem** [comment]
.. par contre dans 2 des 3 cas cités ci-dessus, une méthode très simple résout le problème : les deux premiers chiffres du code ^^  Tout ça semble être organisé par département, donc mettre en jaune "l'ECFR de votre département" résoudrait sûrement déjà pas mal de problèmes. 

Pour le cas 2, pas résolu comme ça, comme tu dis afficher les deux serait déjà pas mal. Je pensais l'avoir fait dans le code mais visiblement non...

**Comment by laem** [comment]
Bon, j'abandonne. Pour Nesle, ma méthode par proximité mais même département donne le résultat suivant : Lieu d'Accueil Unique pour la Rénovation énergétique LAURE à Amiens. 

Donc il semblerait que le "lieu d'accueil unique" ne soit même pas le lieu d'accueil en fait, en plus de pas être unique :smile: 

Comme on le voit sur le [FR Apremis](http://www.association-apremis.org/nos-actions/prevention-de-la-precarite-energetique/conseiller-precarite-energetique), il y a une liste de communautés de communes dans leur giron. 

La base de correspondance semble donc privée et c'est ce qui nous faut.

**Comment by morganmerzouk** [comment]
France rénov fait une requete vers: 
https://france-renov.gouv.fr/espaces-conseil-fr/search.json avec comme payload:
localisation: 80190 - Nesle
insee: 80585
mais si je tente de reproduire en local je n'ai pas de résultat, peut-être pourrait-il nous donner accès à ça

**Comment by laem** [comment]
En attendant d'avoir accès (à nouveau) à une meilleure base de données / API, on a le choix : 
- parier sur le fait que les citoyens vont appeler celui qu'on donne qui les redirigera
- lui montrer plusieurs choix et le laisser décider

**Comment by laem** [comment]
> France rénov fait une requete vers:
> https://france-renov.gouv.fr/espaces-conseil-fr/search.json avec comme payload:
> localisation: 80190 - Nesle
> insee: 80585
> mais si je tente de reproduire en local je n'ai pas de résultat, peut-être pourraient-ils nous donner accès à ça?

C'était en ligne sur notre site, on faisait appel à leur API, mais ils nous ont demandé d'arrêter de le faire, d'où la réimplémentation imparfaite actuelle :/

**Comment by laem** [comment]
en fait je suis même pas sûr que la règle du département soit bonne

genre, une commune enclavée dans un département, ça me parait une idée foireuse de lui demander de faire 100 km au lieu d'aller à l'ECFR à 10 km...

**Comment by laem** [comment]
MAJ : on a trouvé le jeu qui nous manquait https://www.data.gouv.fr/fr/datasets/perimetre-espaces-conseil-france-renov-1/#/information
