### ISSUE TITLE
Problème sur le plafond de l'aide à l'audit MAR

### ISSUE THREAD

**Issue by laem** [betagouv/reno#240]
![image](https://github.com/user-attachments/assets/7090254e-270e-434c-be02-27403710f4cf)

[3:59 PM](https://mattermost.incubateur.net/betagouv/pl/9cuiq1ue4fyefjohqie3ag3rir)

http://localhost:8080/simulation?simulation.mode=%27max%27*&vous.propri%C3%A9taire.statut=%22acqu%C3%A9reur%22*&logement.propri%C3%A9taire+occupant=oui*&logement.r%C3%A9sidence+principale+propri%C3%A9taire=oui*&logement.type=%22appartement%22*&logement.surface=63*&logement.p%C3%A9riode+de+construction=%22au+moins+25+ans%22*&m%C3%A9nage.personnes=1*&m%C3%A9nage.code+r%C3%A9gion=%2253%22*&m%C3%A9nage.code+d%C3%A9partement=%2235%22*&m%C3%A9nage.EPCI=%22243500139%22&m%C3%A9nage.commune=%2235238%22*&taxe+fonci%C3%A8re.commune.%C3%A9ligible.m%C3%A9nage=non&logement.commune.denormandie=non&m%C3%A9nage.revenu=30549*&DPE.actuel=5*&parcours+d%27aide=%22ampleur%22*&details=MPR.accompagn%C3%A9e.prise+en+charge+MAR

**Comment by morganmerzouk** [comment]
@laem En fait cela me semble bon, on fixe un montant moyen de 4000€ pour la prestation du MAR, ménage intermédiaire = 40% de prise en charge donc 1600 au global. Le plafond est à 2000.

**Comment by laem** [comment]
Ah mais oui, je suis bête, j'étais fatigué hier. 

Je pensais que c'était la base qui était plafonnée, en fait d'après ce texte *très ambigu* ce serait le résultat. 

![image](https://github.com/user-attachments/assets/b385b775-cf1c-4390-bac9-37cbd2e83f81)

Donc on peut rester là-dessus.
