### ISSUE TITLE
Page résultat - cas où éligible a un seul parcours

### ISSUE THREAD

**Issue by Mael-21** [betagouv/reno#54]
<img width="937" alt="Capture d’écran 2024-03-19 à 11 26 24" src="https://github.com/betagouv/reno/assets/77799453/fc2a52bc-f8fb-4e47-b8fa-783460fe673c">

Url : https://mesaidesreno.beta.gouv.fr/simulation?conditions+communes=oui*&m%C3%A9nage.personnes=2*&m%C3%A9nage.revenu=70000*&DPE.actuel=6*&projet.DPE+vis%C3%A9=2*&m%C3%A9nage.code+r%C3%A9gion=52*

**Pb :** Intégrer une variable dans la page de résultat de simulation dans le cas ou je ne suis éligible qu'à un seul des deux parcours. 

**Proposition :** 
Remplacer : Vous êtes éligible aux deux parcours, le parcours accompagné et le parcours par gestes. Vous devez choisir l'un des deux parcours. 
Par : 👉 Vous êtes éligible au parcours accompagné /  Vous êtes éligible au parcours par gestes.

**Comment by Mael-21** [comment]
**Pb 2 :** je ne comprends pas pourquoi je ne suis pas éligible à telle parcours.

**Proposition :**  
Intégrer le(s) critère pour lequel je ne suis pas éligible à la box du parcours concerné.

exemple :  🔴  votre revenu fiscal de référence est supérieur à [valeur max]

**Comment by laem** [comment]
Pour le 1, c'était en fait un bug dans le modèle (la ventilation double flux n'était pas sommée comme un montant mais comme un booléen) qui faisait que le texte ne variait pas comme prévu. C'est corrigé.

**Comment by laem** [comment]
Je bosse ça sur #60
