### ISSUE TITLE
Le "sous conditions" perturbe sur l'écran d'éligibilité

### ISSUE THREAD

**Issue by laem** [betagouv/reno#86]
La façon dont "sous conditions" est écrite m'a donné envier de cliquer dessus. Et comme j'ai fait sur mon tel j'ai bien tenté de le toucher 4 ou 5 fois avant de comprendre que les conditions sont à chercher ailleurs 😊

![image](https://github.com/betagouv/reno/assets/1177762/bbbdb333-1481-4d5b-ae1c-d1ea68d5f6ee)

Retour confirmé par un deuxième utilsateur.

**Comment by Mael-21** [comment]
Proposition : supprimer la "sous-condition" (qui n'apparait déjà plus dans les maquette de Jérémie). 
Le "jusqu'à" et le CTA ("affiner mon projet" ou "découvrir le détail") jouent déjà ce rôle d'expliquer qu'il y a des conditions ;)

**Comment by laem** [comment]
Oui c'est une possibilité ! Mais du coup je me demande si on ferait pas mieux, comme la carte "par geste" dans les maquettes, d'afficher directement ici la grille des DPE. 

C->A : 60 % de 70 000 €
D->B : 55 % de 50 000 €
...

Comme ça l'utilisateur capte d'un coup le principe général de l'aide vis-à-vis de l'aide par geste.

**Comment by laem** [comment]
C'est réglé dans la nouvelle version.
