### ISSUE TITLE
Reprendre l'écran d'éligibilité

### ISSUE THREAD

**Issue by laem** [betagouv/reno#88]
![20240403_17h15m11s_grim](https://github.com/betagouv/reno/assets/1177762/30fa5739-0e1d-4247-96da-2a05f01dbae3)

```[tasklist]
### Tasks
- [ ] reprendre le contenu texte @mael-21
```

**Comment by laem** [comment]
Beaucoup de questions : 
- vocabulaire : "à la carte" introduit de nouveaux termes éloignés de ceux de F-R, "20 aides disponibles" éloigne de la compréhension du fait qu'il y a 2 parcours et que c'est "une aide" avec plusieurs gestes : "Voir les 20 gestes financés ?" ?
- on abandonne la liste des avantages qu'il y a en prod ? 
- pas d'iconographie ? 
- pas de cartes visuelles pour séparer les blocs ? 
- quid des aides locales & autres en prod ? 
- quid des explications sur le calcul ?  
-

**Comment by Mael-21** [comment]
Pour moi, la proposition de Jérémie incarne bien la logique du parcours geste. On est moins dans l'explication que dans mise en pratique de la logique du geste. Je suis pour l'intégrer tel quel, en reprenant un peu le texte à la marge pour intégrer un peu d'explication. 
Il faudra sans doute ajouter une logique type "tag" pour intégrer une distinction entre les sources des aides : MPR, CEE, Aide locales...

**Comment by laem** [comment]
@Mael-21 on n'a pas mis de priorité à cette carte. Est-ce qu'elle est P1 ou moins prioritaire ?

**Comment by Mael-21** [comment]
Hey, en effet. Pour moi elle est très prio, c'est le coeur de ce qu'on veut tester avec cette version ;)

**Comment by laem** [comment]
La nouvelle version ampleur a revu entièrement cet écran.
