### ISSUE TITLE
Reprendre l'écran MPRA

### ISSUE THREAD

**Issue by laem** [betagouv/reno#89]
![20240403_17h23m13s_grim](https://github.com/betagouv/reno/assets/1177762/5a85ca7c-ad2a-47c7-a161-5244cd6753c1)

Comme pour l'écran d'éligibilité #88, il faut qu'on confronte cette maquette à l'actuel pour voir quoi remplacer / garder / modifier dans la prod. 
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/reno/issues/92
```

**Comment by laem** [comment]
@Mael-21 @jeremiecook comment vous voyez le choix par défaut du scénario ? Dans la capture ci-dessus, choisir A B C D ou E. 

Ça peut même être une option de l'expliquer avec une petite phrase. 

(Ça ne m'empêche pas de bosser sur l'UI)

**Comment by Mael-21** [comment]
Hello -> proposition de contenu de le ticket https://github.com/betagouv/reno/issues/92

**Comment by Mael-21** [comment]
Quelques retours sur l'intégration : 

#### Dans le bloc Scénario : 
1)
 PB : On a du mal a distinguer la règle (x% jusqu'a y€) de l'exemple. Comment mettre en avant qu'il y a deux niveau de lecture.  
Piste :  est-ce qu'on reprendrait pas le liseré vertical qu'on avait dans la précédente version pour mettre en exergue l'exemple ?
2) 
PB : en première lecture, je ne suis pas certain que l'usager comprennent les "..." qui donnent l'impression que le texte n'est pas terminé
Piste : mettre les ... dans un bloc de couleur pour matérialisé le fait que c'est un champ calculé ?

3) 
Est-ce que cette reformulation en 2 ligne n'est pas plus clair  ? @laem 

Exemple : 
Si j'apporte [mon apport]
Avec l'aide, je dispose d'une enveloppe de [montant calculé] pour réaliser mes travaux. 

#### Information utile 

- J'ajouterai des bullets point pour faciliter la lecture en diagonale
- est-ce qu'on peut faire pointer le lien "en savoir plus" de la première phrase (accompagnateur rénov') vers la FAQ en bas de page vers la question  "quelle sont les grandes étapes" ? (avec une animation scroll down?)

**Comment by laem** [comment]
Fait
