### ISSUE TITLE
[a la carte] décaler la prise de connaissance des maximums

### ISSUE THREAD

**Issue by laem** [betagouv/reno#90]
Je me pose une question nouvelle : est-ce que ces maximums n'étaient pas un guide précieux pour se rendre compte de l'ordre de grandeur du prix du marché des gestes, ainsi que de l'aide ? 

Par exemple pour les fenêtres, on voit que c'est presque rien, alors que pour d'autres c'est 30 %.

**Comment by Mael-21** [comment]
Proposition pour la 1ère MEP : 
- afficher les prix max dans l'écran "ma sélection de geste"

**Comment by laem** [comment]
Beaucoup d'évolutions depuis, c'est obsolète.
