### ISSUE TITLE
[MPRA] Validation des contenu page MPRA @mael-21

### ISSUE THREAD

**Issue by Mael-21** [betagouv/reno#92]
```[tasklist]
### Tasks
- [ ] @mael-21 - valider le contenu texte box simulation
```

**Comment by Mael-21** [comment]
Revue du contenu 👍 


[sur-titre] MaPrimeRénov’ Parcours accompagné
[titre] Financer une rénovation d’ampleur de votre logement

[intro]
Proposition 1
MaPrimeRénov’ Parcours accompagné vous aide à gagner au moins deux classes DPE. 
Vous avez déclaré un DPE [D] -  - [bouton modifier]

Proposition 2 :
Pour bénéficier de cette aide, vous devez viser un saut d’au moins deux classes DPE. 
Vous avez déclaré un DPE [D] - [bouton modifier]

[info]

Informations utiles : 

- Un Accompagnateur Rénov’ réalisera un audit énergétique de votre logement pour définir le projet de travaux vous permettant d’atteindre le DPE visé. [lien en savoir plus vers FR’ - https://france-renov.gouv.fr/preparer-projet/faire-accompagner/mon-accompagnateur-renov]

  - En tant que ménage au revenu très modeste, vous pourrez bénéficier d'une avance de 70 % de la prime, soit 16 800€.

- Vous êtes éligible à l’éco-prêt à taux zéro pour emprunter jusqu’à 50 000 € sur  20 ans


Comment toucher cette aide ?

1)
Vous n’êtes pas encore sûr des travaux à entreprendre ? -> Vous avez encore des questions ?

Un conseiller Ma Prime Rénov’ vous accompagne gratuitement et vous aide à calculer vos aides et votre budget -  Votre conseiller local France Rénov’ vous accompagne gratuitement et sans engagement.  

[CTA] Trouver mon conseiller

2)
Vous voulez lancer votre projet ?

Choisissez votre Accompagnateur Rénov’, l’interlocuteur de confiance agréé par France Rénov’ qui vous accompagne de bout-en-bout dans votre parcours de travaux. 

[CTA] Trouver mon Accompagnateur



Questions fréquentes

Comment choisir les travaux travaux réaliser  ? (Contenu ok)
Quels sont les grandes étape de MaPrimeRénov’ parcours Accompagné  ? (Contenu ok)

Quels sont les conditions pour bénéfice de ma Prime Rénov parcours Accompagné ?

* L’accompagnement par Mon Accompagnateur Rénov’ est obligatoire.
* Un gain de 2 classes énergétiques minimum est exigé. La rénovation énergétique peut être réalisée en 2 étapes tant que la durée des travaux ne dépasse pas 5 ans.
* Il est obligatoire de réaliser au moins deux gestes d’isolation (murs, fenêtres / menuiserie, sols ou toiture). 
* Il est impossible d’installer un chauffage fonctionnant majoritairement aux énergies fossiles ou de conserver un chauffage fonctionnant au fioul ou au charbon.
* Il est obligatoire de vivre dans le logement les 3 années qui suivent la date d’acceptation de la demande d’aide.
* Vos artisans doivent être [certifiés RGE](https://www.ecologie.gouv.fr/label-reconnu-garant-lenvironnement-rge)

Peut-on cumuler Ma Prime  Rénov’ Accompagné avec d’autres aides ?

 Quels sont les délais ?
Y a-t-il des aides locales ?
C’est trop ambitieux pour moi

**Comment by laem** [comment]
OK il reste à revoir les questions réponses.
