### ISSUE TITLE
[éligibilité] Intégration des "autres aides"

### ISSUE THREAD

**Issue by Mael-21** [betagouv/reno#97]
### Écran éligibilité
Comment évoquer les autres aides, celle qui ne sont pas intégré aux simulateurs. 
Certaines ne le sont pas encore, d'autres non pas vocation à l'être. 

Pistes de reflexion : intégrer un nouveau bloc sous les aides à la carte. 

**Les autres aides associées**
Nous travaillons pour les intégrer prochainement au simulateur

Les CEE - + d'info
L’éco-prêt à taux zéro 
Les aides des collectivités locales	
Loc’ avantages
Dispositif Denormandie
Le prêt à l’amélioration de l’habitat (PAH) de la Caisse d’Allocations Familiales (CAF)
```[tasklist]
### Tasks
- [ ] @Mael-21 - reprendre le texte de description des aides
```

**Comment by laem** [comment]
Beaucoup d'évolutions depuis, c'est obsolète.
